apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws
  template:
      metadata:
        labels:
          app: aws
      spec:
        containers:
        - name: aws-cli
          image: amazon/aws-cli:latest
          command: ["sleep",  "3600"]
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        serviceAccountName: "aws-cli-sa"
        volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
